name: Manual Icon Modifier

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Sync icons folder from upstream
      - name: Sync Upstream Icons
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote get-url upstream || git remote add upstream https://github.com/tabler/tabler-icons.git
          git fetch upstream
          git checkout upstream/main -- icons/filled icons/outline
          git add icons/filled icons/outline
          if git diff --cached --quiet; then
            echo "Icons are up to date."
            exit 0
          else
            git checkout -b temp
            git commit -m "Synced Icons"
            git checkout main
            git reset --hard temp
            git push origin main --force
            git branch -d temp
          fi

  process:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      #   Step 1
      #   - Checkout Fork Repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #   Step 2
      #   - Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      #   Step 3
      #   - Install npm packages
      - name: Install Tools
        run: |
          npm install -g oslllo-svg-fixer
          npm install -g svgtofont

      #   Step 4
      #   - Create temp to work on this directory
      #   - Create temp/fixed to fix and store outine icons on this directory
      #   - Create temp/icons to store filled and fixed outline icons on this directory
      - name: Create Temporary Folders
        run: |
          mkdir -pv temp/icons temp/fixed

      #   Step 5
      #   - Fix outline icons from "icons/outline" to "temp/fixed".
      #   - Move outline icons from "temp/fixed" to "temp/icons".
      #   - Rename & Copy filled icons from "icons/filled" to "temp/icons".
      - name: Process Icons
        run: |
          oslllo-svg-fixer --source icons/outline --destination temp/fixed

          for SVG in temp/fixed/*.svg; do
            mv -f $SVG "temp/icons/$(basename "${SVG%.svg}")-outline.svg"
          done

          for SVG in icons/filled/*.svg; do
            mv -f $SVG "temp/icons/$(basename "${SVG%.svg}")-filled.svg"
          done

      #   Step 6
      #   - Convert SVGs to TTF and JSON Map
      - name: Convert Icons
        run: |
          svgtofont --sources temp/icons --output temp --fontName tabler-icons

      #   Step 7
      #   - Get latest tag from upstream
      #   - Create a zip file from temp/icons
      - name: Zip Icons
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/tabler/tabler-icons/releases/latest | jq -r .tag_name)
          echo "TAG=${LATEST_TAG}" >> $GITHUB_ENV

          zip -r temp/tabler-icons.zip temp/icons

      #   Step 8
      #   - Create or Update GitHub Release
      #   - Upload ZIP to GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            temp/tabler-icons.ttf
            temp/tabler-icons.json
            temp/tabler-icons.zip
          name: "Kustom Tabler Icons ${{ env.TAG }}"
          tag_name: ${{ env.TAG }}
