name: Sync Upstream Icons

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your forked repository
      - name: Checkout Fork Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Add and fetch upstream remote
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/tabler/tabler-icons.git
          git fetch upstream

      # Step 3: Check for changes in icons/filled and icons/outline
      - name: Check for Changes
        run: |
          git diff --quiet origin/main upstream/main -- icons/filled/ icons/outline/
        continue-on-error: true

      # Step 4: Exit if no changes
      - name: Exit if No Changes
        if: success()
        run: exit 0

      # Step 5: Sync icons folder from upstream
      - name: Sync Icons Folder
        run: |
          git checkout upstream/main -- icons/filled icons/outline
          git commit -m "Synced icons folders from upstream"
          git push origin main

      # Step 6: Trigger modify-icons.yml
      - name: Trigger Modify Icons Workflow
        if: success()
        run: |
          echo "Triggering processing workflow"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/modify-icons.yml/dispatches \
            -d '{"ref": "main"}'
