name: Sync Fork with Upstream

on:
  # Runs this workflow on a schedule (e.g., once a day) or manually
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your forked repository
      - name: Checkout Fork Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Add upstream repo and fetch updates
      - name: Add and Fetch Upstream
        run: |
          git remote add upstream https://github.com/tabler/tabler-icons.git
          git fetch upstream

      # Step 3: Check for Upstream Changes
      - name: Check for Upstream Changes
        id: check_upstream_changes
        run: |
          UPSTREAM_COMMIT=$(git rev-parse upstream/main)
          FORK_COMMIT=$(git rev-parse origin/main)

          if [ "$UPSTREAM_COMMIT" = "$FORK_COMMIT" ]; then
            echo "No upstream changes detected. Exiting."
            exit 0
          else
            echo "Upstream changes detected. Proceeding with the workflow."
          fi

      # Step 4: Rebase fork with upstream
      - name: Rebase Fork with Upstream
        run: |
          git checkout main
          git rebase upstream/main
          git push --force-with-lease origin main

      # Step 5: Trigger Processing Workflow (using `workflow_run`)
      - name: Trigger Processing Workflow
        if: success()
        run: |
          echo "Triggering processing workflow"
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/process-icons.yml/dispatches \
            -d '{"ref": "main"}'
